package es.digimap.thor;

/** Stable species and technique IDs; UI labels do not depend on a ROM font encoding. */
final class DataNames {
  static final String[] DIGIMON = {
    "Héroe",
    "Botamon",
    "Koromon",
    "Agumon",
    "Betamon",
    "Greymon",
    "Devimon",
    "Airdramon",
    "Tyrannomon",
    "Meramon",
    "Seadramon",
    "Numemon",
    "MetalGreymon",
    "Mamemon",
    "Monzaemon",
    "Punimon",
    "Tsunomon",
    "Gabumon",
    "Elecmon",
    "Kabuterimon",
    "Angemon",
    "Birdramon",
    "Garurumon",
    "Yukidarumon",
    "Whamon",
    "Vegimon",
    "SkullGreymon",
    "MetalMamemon",
    "Vademon",
    "Poyomon",
    "Tokomon",
    "Patamon",
    "Kunemon",
    "Unimon",
    "Ogremon",
    "Shellmon",
    "Centarumon",
    "Bakemon",
    "Drimogemon",
    "Sukamon",
    "Andromon",
    "Giromon",
    "Etemon",
    "Yuramon",
    "Tanemon",
    "Piyomon",
    "Palmon",
    "Monochromon",
    "Leomon",
    "Coelamon",
    "Cockatrimon",
    "Kuwagamon",
    "Mojyamon",
    "Nanimon",
    "Megadramon",
    "Piccolomon",
    "Digitamamon",
    "Penmon",
    "Igamon",
    "Hououmon",
    "HerculesKabuterimon",
    "MegaSeadramon",
    "WereGarurumon",
    "Panjyamon",
    "Gigadramon",
    "MetalEtemon",
    "Myotismon",
    "Yanmamon",
    "Gotsumon",
    "Flarerizamon",
    "WaruMonzaemon",
    "SnowAgumon",
    "Hyogamon",
    "PlatinumSukamon",
    "Dokunemon",
    "ShimaUnimon",
    "Tankmon",
    "RedVegiemon",
    "JungleMojyamon",
    "NiseDrimogemon",
    "Goburimon",
    "MudFrigimon",
    "Psychemon",
    "ModokiBetamon",
    "ToyAgumon",
    "Piddomon",
    "Aruraumon",
    "Geremon",
    "Vermilimon",
    "Fugamon",
    "Tekkamon",
    "MoriShellmon",
    "Guardromon",
    "Muchomon",
    "Icemon",
    "Akatorimon",
    "Tsukaimon",
    "Sharmamon",
    "ClearAgumon",
    "Weedmon",
    "IceDevimon",
    "Darkrizamon",
    "SandYanmamon",
    "SnowGoburimon",
    "BlueMeramon",
    "Gururumon",
    "Saberdramon",
    "Soulmon",
    "Rockmon",
    "Otamamon",
    "Gekomon",
    "Tentomon",
    "WaruSeadramon",
    "Meteormon",
    "",
    "Machinedramon",
    "Analogman",
    "Jijimon",
    "Market Manager",
    "ShogunGekomon",
    "King of Sukamon",
    "Cherrymon",
    "Hagurumon",
    "Tinmon",
    "Master Tyrannomon",
    "Goburimon",
    "Brachiomon",
    "DemiMeramon",
    "Betamon",
    "Greymon",
    "Devimon",
    "Airdramon",
    "Tyrannomon",
    "Meramon",
    "Seadramon",
    "Numemon",
    "MetalGreymon",
    "Mamemon",
    "Monzaemon",
    "Gabumon",
    "Elecmon",
    "Kabuterimon",
    "Angemon",
    "Birdramon",
    "Garurumon",
    "Yukidarumon",
    "Whamon",
    "Vegimon",
    "SkullGreymon",
    "MetalMamemon",
    "Vademon",
    "Patamon",
    "Kunemon",
    "Unimon",
    "Ogremon",
    "Shellmon",
    "Centarumon",
    "Bakemon",
    "Drimogemon",
    "Sukamon",
    "Andromon",
    "Giromon",
    "Etemon",
    "Piyomon",
    "Palmon",
    "Monochromon",
    "Leomon",
    "Coelamon",
    "Cockatrimon",
    "Kuwagamon",
    "Mojyamon",
    "Nanimon",
    "Megadramon",
    "Piccolomon",
    "Digitamamon",
    "Igamon",
    "Penmon",
    "Myotismon",
    "Greymon",
    "MetalGreymon"
  };
  static final String[] TECHNIQUES = {
    "Torre de fuego",
    "Rayo de prominencia",
    "Escupir fuego",
    "Infierno rojo",
    "Bomba de magma",
    "Láser de calor",
    "Fuego infinito",
    "Fusión",
    "Justicia del trueno",
    "Disparo giratorio",
    "Nube eléctrica",
    "Megachispa",
    "Electricidad estática",
    "Cortaviento",
    "Tormenta confusa",
    "Huracán",
    "Congelación gigante",
    "Estatua de hielo",
    "Ráfaga invernal",
    "Aguja de hielo",
    "Disparo de agua",
    "Magia acuática",
    "Congelación aurora",
    "Gota de lágrima",
    "Grúa de fuerza",
    "Rayo omnidireccional",
    "Velocista metálico",
    "Láser de pulsos",
    "Borrar programa",
    "Dimensión DG",
    "Potencial completo",
    "Programa inverso",
    "Polvo venenoso",
    "Bicho",
    "Metamorfosis",
    "Plaga de insectos",
    "Perfume encantador",
    "Garra venenosa",
    "Aguijón peligroso",
    "Trampa verde",
    "Temblor",
    "Carga muscular",
    "Grito de guerra",
    "Puñetazo sónico",
    "Patada dinamita",
    "Contraataque",
    "Puñetazo megatón",
    "Zambullida brutal",
    "Patada dinamita",
    "Spray de olor",
    "Lanzamiento rápido",
    "Gran lanzamiento",
    "Gran lanzamiento aleatorio",
    "Lanzamiento aleatorio",
    "Lanzamiento veloz aleatorio",
    "Patada horizontal",
    "Infierno de suciedad",
    "Patada horizontal"
  };
  static final String[] ZONES = {
    "Bosque nativo",
    "Cabo Coela",
    "Lago Ojo del Dragón",
    "Entrada del túnel taladro",
    "Puente Digimon",
    "Selva tropical",
    "Manglares",
    "Camino del monte Panorama",
    "Entrada de Ciudad File",
    "Llanura del monte Panorama",
    "Pie del monte Panorama",
    "Zona de esporas",
    "Túnel taladro",
    "Túnel taladro · planta 2",
    "Túnel taladro · planta 3",
    "Zona residencial",
    "Estanque subterráneo",
    "Cueva de lava",
    "Overdell",
    "Cementerio de Overdell",
    "Entrada del gran cañón",
    "Cima del gran cañón",
    "Puente del gran cañón",
    "Entrada de la fortaleza",
    "Fondo del gran cañón",
    "Fortaleza de Ogremon",
    "Tienda de Monochromon",
    "Mansión del señor gris",
    "Sótano de la mansión",
    "Laboratorio subterráneo",
    "Sabana de engranajes",
    "Región de dinosaurios",
    "Región glacial antigua",
    "Región rápida antigua",
    "Tierra helada",
    "Santuario de hielo",
    "Gimnasio verde",
    "Cueva ancestral de Leomon",
    "Árboles de niebla",
    "Gran cañón",
    "Tierra helada",
    "Pantano Geko",
    "Villa del volumen",
    "Ciudad File",
    "Almacén de objetos",
    "Clínica Centarumon",
    "Restaurante",
    "Tienda de objetos",
    "Casa de Jijimon",
    "Tienda secreta",
    "Ciudad juguete",
    "Cueva de la playa secreta",
    "Ciudad factorial",
    "Transporte Birdramon",
    "Vestíbulo del estadio",
    "Búsqueda del tesoro",
    "Montaña de basura",
    "Alcantarilla",
    "Tierra de escarabajos",
    "Monte infinito",
    "Curling Digimon",
    "Mansión de juguetes",
    "Casa de disfraces",
    "Casa de robots",
    "Mansión · planta 2",
    "Ático de la mansión",
    "Sótano de la mansión",
    "Dimensión trasera",
    "Lecho de Kunemon",
    "Bosque Amida"
  };
  static final String[] ITEMS = {
    "Recuperación pequeña",
    "Recuperación mediana",
    "Recuperación grande",
    "Superrecuperación",
    "Disco de PM",
    "Disco de PM mediano",
    "Disco de PM grande",
    "Disco doble",
    "Disco múltiple",
    "Disco omnipotente",
    "Protección",
    "Restaurador",
    "Superrestaurador",
    "Venda",
    "Medicina",
    "Disco de ataque",
    "Disco de defensa",
    "Disco de velocidad",
    "Disco omni",
    "Superdisco de ataque",
    "Superdisco de defensa",
    "Superdisco de velocidad",
    "Piloto automático",
    "Chip de ataque",
    "Chip de defensa",
    "Chip de inteligencia",
    "Chip de velocidad",
    "Chip de PV",
    "Chip de PM",
    "Chip DV A",
    "Chip DV D",
    "Chip DV E",
    "WC portátil",
    "Manual de entrenamiento",
    "Almohada de descanso",
    "Repelente de enemigos",
    "Campana de enemigos",
    "Zapatos saludables",
    "Carne",
    "Carne gigante",
    "Solomillo",
    "Superzanahoria",
    "Rábano halcón",
    "Verdura espinosa",
    "Digiseta",
    "Seta helada",
    "Seta de lujo",
    "Digipino",
    "Manzana azul",
    "Baya roja",
    "Bellota dorada",
    "Baya grande",
    "Nuez dulce",
    "Superverdura",
    "Higo chumbo",
    "Plátano naranja",
    "Fruta de poder",
    "Hielo de poder",
    "Hoja veloz",
    "Fruta sabia",
    "Ñame muscular",
    "Baya calmante",
    "Digianchoa",
    "Digipargo",
    "Digitrucha",
    "Trucha negra",
    "Digisiluro",
    "Digilubina",
    "Carne mohosa",
    "Seta de felicidad",
    "Melón encadenado",
    "Garras grises",
    "Bola de fuego",
    "Ala llameante",
    "Pezuña de hierro",
    "Piedra mono",
    "Taladro de acero",
    "Colmillo blanco",
    "Ala negra",
    "Maza con pinchos",
    "Melena llameante",
    "Ala blanca",
    "Trapo rasgado",
    "Anillo eléctrico",
    "Cuerno arcoíris",
    "Gallo",
    "Cuerno único",
    "Casco con cuernos",
    "Mandíbula tijera",
    "Fertilizante",
    "Garras Koga",
    "Botella de agua",
    "Estrella del norte",
    "Caparazón rojo",
    "Escama dura",
    "Cristal azul",
    "Cristal de hielo",
    "Crecepelo",
    "Gafas de sol",
    "Pieza metálica",
    "Hueso fatal",
    "Pieza cibernética",
    "Megamano",
    "Bola de plata",
    "Armadura metálica",
    "Motosierra",
    "Lanza pequeña",
    "Venda X",
    "Pistola de rayos",
    "Plátano dorado",
    "Huevo misterioso",
    "Rubí rojo",
    "Perla escarabajo",
    "Amuleto de coral",
    "Espejo lunar",
    "Flauta azul",
    "Caña vieja",
    "Caña increíble",
    "Piedra de Leomon",
    "Llave de la mansión",
    "Engranaje",
    "Planta de lluvia",
    "Bistec",
    "Llave del frigorífico",
    "Decodificador AS",
    "Gigamano",
    "Melena noble",
    "Plátano metálico"
  };
}
